(print (reverse '(a b c)) )
(print (reverse '(a b (c (d)))) )
(print (reverse '(a)) )
(print (reverse ()) )
(print (reverse '((a b c))) )
(print (last '(a b c)) )
(print (last '(a)) )
(print (last '((a b c))) )
(print (last '(a b (c))) )
(print (last ()) )